---
- name: Deploy Kubernetes Pods
  hosts: servers
  become: yes

  tasks:

    - name: Create Kubernetes directory
      file:
        path: /home/ubuntu/kubernetes
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Copy Kubernetes files
      copy:
        src: "{{ playbook_dir }}/roles/kubernetes/"
        dest: /home/ubuntu/kubernetes/
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Create ECR secret
      become_user: ubuntu
      shell: |
        kubectl create secret docker-registry ecr-secret \
          --docker-server=025232685400.dkr.ecr.ap-south-1.amazonaws.com \
          --docker-username=AWS \
          --docker-password="$(aws ecr get-login-password --region ap-south-1)" \
          --dry-run=client -o yaml | kubectl apply -f -
      args:
        executable: /bin/bash

    - name: Deploy Application
      become_user: ubuntu
      command:
        cmd: kubectl apply -f /home/ubuntu/kubernetes/app-pod.yaml

    - name: Deploy Prometheus Config
      become_user: ubuntu
      command:
        cmd: kubectl apply -f /home/ubuntu/kubernetes/prometheus-config.yaml

    - name: Deploy Prometheus
      become_user: ubuntu
      command:
        cmd: kubectl apply -f /home/ubuntu/kubernetes/prometheus-pod.yaml

    - name: Deploy Grafana
      become_user: ubuntu
      command:
        cmd: kubectl apply -f /home/ubuntu/kubernetes/grafana-pod.yaml

    - name: Check Pods
      become_user: ubuntu
      command:
        cmd: kubectl get pods -o wide
      register: pod_status

    - name: Display Pod Status
      debug:
        var: pod_status.stdout_lines

